//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGreenwheels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GreenwheelsEntities : DbContext
    {
        public GreenwheelsEntities()
            : base("name=GreenwheelsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TypeSubscription> TypeSubscriptions { get; set; }
        public virtual DbSet<TypeVehicle> TypeVehicles { get; set; }
        public virtual DbSet<Tariff> Tariffs { get; set; }
    }
}
